#
# Generated file -- DO NOT EDIT
#
# constants.py -- Useful constants extracted from Gmail Javascript code
#
# Source version: 44f09303f2d4f76f
#
# Generated: 2004-07-10 18:15 UTC
#

js_version = '44f09303f2d4f76f'

D_VERSION = "v"
D_QUOTA = "qu"
D_DEFAULTSEARCH_SUMMARY = "ds"
D_THREADLIST_SUMMARY = "ts"
D_THREADLIST_END = "te"
D_THREAD = "t"
D_CONV_SUMMARY = "cs"
D_CONV_END = "ce"
D_MSGINFO = "mi"
D_MSGBODY = "mb"
D_MSGATT = "ma"
D_COMPOSE = "c"
D_CONTACT = "co"
D_CATEGORIES = "ct"
D_CATEGORIES_COUNT_ALL = "cta"
D_ACTION_RESULT = "ar"
D_SENDMAIL_RESULT = "sr"
D_PREFERENCES = "p"
D_PREFERENCES_PANEL = "pp"
D_FILTERS = "fi"
D_GAIA_NAME = "gn"
D_INVITE_STATUS = "i"
D_END_PAGE = "e"
D_LOADING = "l"
D_LOADED_SUCCESS = "ld"
D_LOADED_ERROR = "le"
D_QUICKLOADED = "ql"
QU_SPACEUSED = 0
QU_QUOTA = 1
QU_PERCENT = 2
QU_COLOR = 3
TS_START = 0
TS_NUM = 1
TS_TOTAL = 2
TS_ESTIMATES = 3
TS_TITLE = 4
TS_TIMESTAMP = 5
TS_TOTAL_MSGS = 6
T_THREADID = 0
T_UNREAD = 1
T_STAR = 2
T_DATE_HTML = 3
T_AUTHORS_HTML = 4
T_FLAGS = 5
T_SUBJECT_HTML = 6
T_SNIPPET_HTML = 7
T_CATEGORIES = 8
T_ATTACH_HTML = 9
T_MATCHING_MSGID = 10
T_EXTRA_SNIPPET = 11
CS_THREADID = 0
CS_SUBJECT = 1
CS_TITLE_HTML = 2
CS_SUMMARY_HTML = 3
CS_CATEGORIES = 4
CS_PREVNEXTTHREADIDS = 5
CS_THREAD_UPDATED = 6
CS_NUM_MSGS = 7
CS_ADKEY = 8
CS_MATCHING_MSGID = 9
MI_FLAGS = 0
MI_NUM = 1
MI_MSGID = 2
MI_STAR = 3
MI_REFMSG = 4
MI_AUTHORNAME = 5
MI_AUTHOREMAIL = 6
MI_MINIHDRHTML = 7
MI_DATEHTML = 8
MI_TO = 9
MI_CC = 10
MI_BCC = 11
MI_REPLYTO = 12
MI_DATE = 13
MI_SUBJECT = 14
MI_SNIPPETHTML = 15
MI_ATTACHINFO = 16
MI_KNOWNAUTHOR = 17
MI_PHISHWARNING = 18
U_SEARCH = "search"
U_INBOX_SEARCH = "inbox"
U_STARRED_SEARCH = "starred"
U_ALL_SEARCH = "all"
U_DRAFTS_SEARCH = "drafts"
U_SENT_SEARCH = "sent"
U_SPAM_SEARCH = "spam"
U_TRASH_SEARCH = "trash"
U_QUERY_SEARCH = "query"
U_ADVANCED_SEARCH = "adv"
U_CREATEFILTER_SEARCH = "cf"
U_CATEGORY_SEARCH = "cat"
