#
# Generated file -- DO NOT EDIT
#
# constants.py -- Useful constants extracted from Gmail Javascript code
#
# Source version: 9bb15b436c55eb41
#
# Generated: 2004-07-03 17:10 UTC
#

js_version = '9bb15b436c55eb41'

D_VERSION = "v"
D_QUOTA = "qu"
D_DEFAULTSEARCH_SUMMARY = "ds"
D_THREADLIST_SUMMARY = "ts"
D_THREADLIST_END = "te"
D_THREAD = "t"
D_CONV_SUMMARY = "cs"
D_CONV_END = "ce"
D_MSGINFO = "mi"
D_MSGBODY = "mb"
D_MSGATT = "ma"
D_CONTACT = "co"
D_CATEGORIES = "ct"
D_CATEGORIES_COUNT_ALL = "cta"
D_ACTION_RESULT = "ar"
D_SENDMAIL_RESULT = "sr"
D_PREFERENCES = "p"
D_PREFERENCES_PANEL = "pp"
D_FILTERS = "fi"
D_GAIA_NAME = "gn"
D_INVITE_STATUS = "i"
D_END_PAGE = "e"
D_LOADING = "l"
D_LOADED_SUCCESS = "ld"
D_LOADED_ERROR = "le"
D_QUICKLOADED = "ql"
QU_SPACEUSED = 1
QU_QUOTA = 2
QU_PERCENT = 3
QU_COLOR = 4
TS_START = 1
TS_NUM = 2
TS_TOTAL = 3
TS_ESTIMATES = 4
TS_TITLE = 5
TS_TIMESTAMP = 6
TS_TOTAL_MSGS = 7
T_THREADID = 0
T_UNREAD = 1
T_STAR = 2
T_DATE_HTML = 3
T_AUTHORS_HTML = 4
T_FLAGS = 5
T_SUBJECT_HTML = 6
T_SNIPPET_HTML = 7
T_CATEGORIES = 8
T_ATTACH_HTML = 9
T_MATCHING_MSGID = 10
T_EXTRA_SNIPPET = 11
CS_THREADID = 1
CS_SUBJECT = 2
CS_TITLE_HTML = 3
CS_SUMMARY_HTML = 4
CS_CATEGORIES = 5
CS_PREVNEXTTHREADIDS = 6
CS_THREAD_UPDATED = 7
CS_NUM_MSGS = 8
CS_ADKEY = 9
CS_MATCHING_MSGID = 10
MI_FLAGS = 1
MI_NUM = 2
MI_MSGID = 3
MI_STAR = 4
MI_REFMSG = 5
MI_AUTHORNAME = 6
MI_AUTHOREMAIL = 7
MI_MINIHDRHTML = 8
MI_DATEHTML = 9
MI_TO = 10
MI_CC = 11
MI_BCC = 12
MI_REPLYTO = 13
MI_DATE = 14
MI_SUBJECT = 15
MI_SNIPPETHTML = 16
MI_ATTACHINFO = 17
MI_KNOWNAUTHOR = 18
MI_PHISHWARNING = 19
